// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrksdiolutdlldkazzji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFya3NkaW9sdXRkbGxka2F6emppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTcxMTIsImV4cCI6MjA3MzkzMzExMn0.RsJVBmkrhXBO26YNU-GzOhPPNSIbUfIMVmac-941fTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});